# Generated by Django 3.1.7 on 2021-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
