# Generated by Django 3.1.7 on 2021-03-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
