# Generated by Django 3.1.7 on 2021-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='featureimg',
            field=models.FileField(default=1, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
