# Generated by Django 3.1.7 on 2021-03-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact_featureimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='featureimg',
        ),
    ]
