# Generated by Django 3.1.7 on 2021-03-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_remove_contact_featureimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='extUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=15)),
                ('profileimg', models.ImageField(default='/profile/images/defaultp.jpg', max_length=500, upload_to='profile/images')),
                ('age', models.IntegerField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
