# Generated by Django 3.1.7 on 2021-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_extuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
