# Generated by Django 3.1.7 on 2021-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featureimg',
            field=models.FileField(default=1, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
