# Generated by Django 3.1.7 on 2021-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featureimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featureimg',
            field=models.ImageField(max_length=500, upload_to='post/featureimg'),
        ),
    ]
