# Generated by Django 3.1.7 on 2021-03-13 07:22

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
