# Generated by Django 3.1.7 on 2021-03-13 07:47

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210313_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True),
        ),
    ]
