# Generated by Django 3.1.7 on 2021-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postcategory',
            field=models.CharField(default='Mobile Games', max_length=50, verbose_name=models.CharField(default='PC Games', max_length=20)),
        ),
    ]
