# Generated by Django 3.1.7 on 2021-03-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
